### ISSUE TITLE
Missing item in inventory

### ISSUE THREAD

**Issue by LeiRoF** [Gunivers/Scaffolding-Rush#11]
When a player place blocks too quickly, the client inventory can be desynchronised from the server one. The player have to press the drop key to fixe the issue manually.

Possible sollution to fix:

- Put a stack of blocs instead of 1 (not fancy)
- Have a genius idea to detect the desynchronization and then clear the bloc and regive it

**Comment by Loumardes** [comment]
I increased stack count
I also believe that it was the spawn protection that cause the item loss
