### ISSUE TITLE
Les blocs en train de tomber peuvent drop un item

### ISSUE THREAD

**Issue by Loumardes** [Gunivers/Scaffolding-Rush#129]
clear ces items dans l'inventaire (ils n'ont pas de tags)

**Comment by VForiel** [comment]
Les items doivent être kill

⚠ Lorsque le joueur drop ses items, ces derniers ne doivent pas être kill avant qu'il les récupère via le système d'anti-drop présent dans la boucle principale. Ces items doivent alors êtres identifié par un nouveau tag pour être exclu du système de clear des items
