### ISSUE TITLE
Mettre le joueur qui tient le villageois en glowing

### ISSUE THREAD

**Issue by VForiel** [Gunivers/Scaffolding-Rush#151]
Permettre d'identifier les joueurs qui ont le villageois en les mettant en glowing afin d'éviter la question éternelle "euh, qui a le vilalgeois ?" et permettre à l'équipe adverse de cibler la bonne personne

**Comment by Theaustudio** [comment]
pq pas.
Ça pourrait être marrant de mettre le villageois sur la tête du joueur quand il a l'oeuf
