### ISSUE TITLE
game bug when pushing the start button during /reload

### ISSUE THREAD

**Issue by TretinV3** [Gunivers/Scaffolding-Rush#42]
![2022-08-21_11 57 19](https://user-images.githubusercontent.com/86251078/185785792-a9fa942e-cf31-4b57-b431-4f99760153d8.png)
![2022-08-21_11 56 44](https://user-images.githubusercontent.com/86251078/185785797-c6ed1997-4792-474f-b02d-4abde9071c1a.png)

**Comment by Theaustudio** [comment]
Ce bug provient lorsque le mode de développement est activé (`DevelopementMode`), ce qui autorise le lancement de la partie même si un reset est en cours

This bug occurs when development mode is enabled (`DevelopmentMode`), which allows the game to run even if a reset is in progress

**Comment by Loumardes** [comment]
intéressant, dans ce cas il n'y a pas trop besoin de le régler, à condition que les utilisateurs ne soient pas amenés à l'utiliser

**Comment by Theaustudio** [comment]
Je vais faire un petit fix vite fait
