### ISSUE TITLE
player spawning in the base and can't jump becase of the /effect

### ISSUE THREAD

**Issue by TretinV3** [Gunivers/Scaffolding-Rush#43]

**Comment by Theaustudio** [comment]
Après que la partie est commencée ou pendant le compte à rebours ?
Si c'est pendant le compte à rebours, c'est fait exprès pour éviter de sortir de la base
This is done on purpose to prevent them from leaving the base

**Comment by ascpial** [comment]
Du coup le problème n'est pas de pas pouvoir sauter mais est que les bases ne spawnent par correctement

**Comment by Theaustudio** [comment]
Fix with https://github.com/Gunivers/Scaffolding-Rush/commit/5294418e5dd357e20c967dc4e54fb51b8b551e12
